<?php //[STAMP] 9c7ff5c63929de418217ca2e0d4d07e5

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void haveFriend($name, $actorClass = null)
 * @method void comment($description)
 * @method void expect($prediction)
 * @method void lookForwardTo($achieveValue)
 * @method void expectTo($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
*/
class UnitTester extends \Codeception\Actor
{
}
