<?php //[STAMP] 3d860a7e8ac10152cda97446a9a2da4a

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use Codeception\Module\Asserts;
use Codeception\Module\UnitHelper;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void haveFriend($name, $actorClass = null)
 * @method void comment($description)
 * @method void expect($prediction)
 * @method void lookForwardTo($achieveValue)
 * @method void expectTo($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
*/
class UnitTester extends \Codeception\Actor
{
   
}
